### ISSUE TITLE
【VectorAPI】aarch64平台fastdebug版本运行compiler/vectorapi/VectorReinterpretTest.java必现crash：assert(Matcher::vector_size_supported(elem_bt, length)) failed: length in range

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#530]
test command：
```bash
jtreg -va -nr -w tmp jdk-repo/test/hotspot/jtreg/compiler/vectorapi/VectorReinterpretTest.java
```

result:
```log
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/type.cpp:2359
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/yansendao/git/dragonwell11/src/hotspot/share/opto/type.cpp:2359), pid=564067, tid=564250
#  assert(Matcher::vector_size_supported(elem_bt, length)) failed: length in range
#
# JRE version: OpenJDK Runtime Environment (11.0.18) (fastdebug build 11.0.18-internal+0-adhoc.yansendao.dragonwell11)
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 11.0.18-internal+0-adhoc.yansendao.dragonwell11, mixed mode, tiered, compressed oops, g1 gc, linux-aarch64)
# Core dump will be written. Default location: /tmp/tone/run/jtreg/tmp/scratch/core.564067
#
# An error report file with more information is saved as:
# /tmp/tone/run/jtreg/tmp/scratch/hs_err_pid564067.log
#
# Compiler replay data is saved as:
# /tmp/tone/run/jtreg/tmp/scratch/replay_pid564067.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Current thread is 564250
Dumping core ...
STDERR:
WARNING: Using incubator modules: jdk.incubator.vector
rerun:
cd /tmp/tone/run/jtreg/tmp/scratch && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/tmp/classes/compiler/vectorapi/VectorReinterpretTest.d:/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/compiler/vectorapi:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /tmp/tone/run/jtreg/binary-download/openjdk-11.0.18-pr528-aarch64-fastdebug/bin/java \
        -Dtest.vm.opts= \
        -Dtest.tool.vm.opts= \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/openjdk-11.0.18-pr528-aarch64-fastdebug \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/openjdk-11.0.18-pr528-aarch64-fastdebug \
        -Dtest.timeout.factor=1.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg \
        -Dtest.name=compiler/vectorapi/VectorReinterpretTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/compiler/vectorapi/VectorReinterpretTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/compiler/vectorapi \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/compiler/vectorapi \
        -Dtest.classes=/tmp/tone/run/jtreg/tmp/classes/compiler/vectorapi/VectorReinterpretTest.d \
        -Dtest.class.path=/tmp/tone/run/jtreg/tmp/classes/compiler/vectorapi/VectorReinterpretTest.d \
        -Dtest.modules=jdk.incubator.vector \
        --add-modules jdk.incubator.vector \
        -Xbatch \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/tmp/compiler/vectorapi/VectorReinterpretTest.d/main.0.jta

TEST RESULT: Failed. Unexpected exit from test [exit code: 134]
```

[replay_pid789646.log](https://github.com/dragonwell-project/dragonwell11/files/11119244/replay_pid789646.log)
[hs_err_pid789646.log](https://github.com/dragonwell-project/dragonwell11/files/11119245/hs_err_pid789646.log)
[core.789646.tar.bz2.log](https://github.com/dragonwell-project/dragonwell11/files/11119246/core.789646.tar.bz2.log)

**Comment by sendaoYan** [comment]
compiler/vectorapi/TestVectorShuffleIotaByte用例现象一样

**Comment by JoshuaZhuwj** [comment]
> compiler/vectorapi/TestVectorShuffleIotaByte用例现象一样

好的，应该还会有些类似的。

**Comment by sendaoYan** [comment]
相同现象的用例：

```log
jdk/incubator/vector/Byte256VectorLoadStoreTests.java
jdk/incubator/vector/Byte512VectorLoadStoreTests.java
jdk/incubator/vector/Double256VectorLoadStoreTests.java
jdk/incubator/vector/Double512VectorLoadStoreTests.java
jdk/incubator/vector/Byte256VectorTests.java
jdk/incubator/vector/Byte512VectorTests.java
jdk/incubator/vector/Float256VectorLoadStoreTests.java
jdk/incubator/vector/Double512VectorTests.java
jdk/incubator/vector/Double256VectorTests.java
jdk/incubator/vector/Float512VectorLoadStoreTests.java
jdk/incubator/vector/Float256VectorTests.java
jdk/incubator/vector/Float512VectorTests.java
jdk/incubator/vector/Int256VectorLoadStoreTests.java
jdk/incubator/vector/Int256VectorTests.java
jdk/incubator/vector/Int512VectorLoadStoreTests.java
jdk/incubator/vector/Int512VectorTests.java
jdk/incubator/vector/Long256VectorLoadStoreTests.java
jdk/incubator/vector/Long512VectorTests.java
jdk/incubator/vector/Long512VectorLoadStoreTests.java
jdk/incubator/vector/Long256VectorTests.java
jdk/incubator/vector/MismatchTest.java
jdk/incubator/vector/Short256VectorLoadStoreTests.java
jdk/incubator/vector/Short256VectorTests.java
jdk/incubator/vector/Short512VectorLoadStoreTests.java
jdk/incubator/vector/Short512VectorTests.java
jdk/incubator/vector/Vector256ConversionTests.java
jdk/incubator/vector/Vector512ConversionTests.java
jdk/incubator/vector/VectorReshapeTests.java
```

[hs_err_pid2829330.log](https://github.com/dragonwell-project/dragonwell11/files/11134367/hs_err_pid2829330.log)
[hs_err_pid2829119.log](https://github.com/dragonwell-project/dragonwell11/files/11134368/hs_err_pid2829119.log)
[hs_err_pid2828993.log](https://github.com/dragonwell-project/dragonwell11/files/11134369/hs_err_pid2828993.log)
[hs_err_pid2828658.log](https://github.com/dragonwell-project/dragonwell11/files/11134370/hs_err_pid2828658.log)
[hs_err_pid2828503.log](https://github.com/dragonwell-project/dragonwell11/files/11134371/hs_err_pid2828503.log)
[hs_err_pid2828373.log](https://github.com/dragonwell-project/dragonwell11/files/11134372/hs_err_pid2828373.log)
[hs_err_pid2828320.log](https://github.com/dragonwell-project/dragonwell11/files/11134373/hs_err_pid2828320.log)
[hs_err_pid2828042.log](https://github.com/dragonwell-project/dragonwell11/files/11134374/hs_err_pid2828042.log)
[hs_err_pid2827695.log](https://github.com/dragonwell-project/dragonwell11/files/11134375/hs_err_pid2827695.log)
[hs_err_pid2827630.log](https://github.com/dragonwell-project/dragonwell11/files/11134376/hs_err_pid2827630.log)
[hs_err_pid2827618.log](https://github.com/dragonwell-project/dragonwell11/files/11134377/hs_err_pid2827618.log)
[hs_err_pid2827487.log](https://github.com/dragonwell-project/dragonwell11/files/11134378/hs_err_pid2827487.log)
[hs_err_pid2826785.log](https://github.com/dragonwell-project/dragonwell11/files/11134379/hs_err_pid2826785.log)
[hs_err_pid2826676.log](https://github.com/dragonwell-project/dragonwell11/files/11134380/hs_err_pid2826676.log)
[hs_err_pid2826512.log](https://github.com/dragonwell-project/dragonwell11/files/11134383/hs_err_pid2826512.log)
[hs_err_pid2826429.log](https://github.com/dragonwell-project/dragonwell11/files/11134384/hs_err_pid2826429.log)
[hs_err_pid2825813.log](https://github.com/dragonwell-project/dragonwell11/files/11134385/hs_err_pid2825813.log)
[hs_err_pid2825749.log](https://github.com/dragonwell-project/dragonwell11/files/11134386/hs_err_pid2825749.log)
[hs_err_pid2825627.log](https://github.com/dragonwell-project/dragonwell11/files/11134387/hs_err_pid2825627.log)
[hs_err_pid2825535.log](https://github.com/dragonwell-project/dragonwell11/files/11134388/hs_err_pid2825535.log)
[hs_err_pid2825475.log](https://github.com/dragonwell-project/dragonwell11/files/11134389/hs_err_pid2825475.log)
[hs_err_pid2825274.log](https://github.com/dragonwell-project/dragonwell11/files/11134390/hs_err_pid2825274.log)
[hs_err_pid2825145.log](https://github.com/dragonwell-project/dragonwell11/files/11134391/hs_err_pid2825145.log)
[hs_err_pid2824998.log](https://github.com/dragonwell-project/dragonwell11/files/11134392/hs_err_pid2824998.log)
[hs_err_pid2824971.log](https://github.com/dragonwell-project/dragonwell11/files/11134393/hs_err_pid2824971.log)
[hs_err_pid2824841.log](https://github.com/dragonwell-project/dragonwell11/files/11134394/hs_err_pid2824841.log)
[hs_err_pid2824691.log](https://github.com/dragonwell-project/dragonwell11/files/11134395/hs_err_pid2824691.log)
[hs_err_pid2824473.log](https://github.com/dragonwell-project/dragonwell11/files/11134396/hs_err_pid2824473.log)
[hs_err_pid2823889.log](https://github.com/dragonwell-project/dragonwell11/files/11134397/hs_err_pid2823889.log)
[hs_err_pid259035.log](https://github.com/dragonwell-project/dragonwell11/files/11134398/hs_err_pid259035.log)
[hs_err_pid258896.log](https://github.com/dragonwell-project/dragonwell11/files/11134399/hs_err_pid258896.log)

**Comment by JoshuaZhuwj** [comment]
收到，谢谢！

**Comment by JoshuaZhuwj** [comment]
Fixed.
