### ISSUE TITLE
[TESTBUG]["11.0.19.14" 2023-04-18]runtime/appcds/TestCombinedCompressedFlags.java用例报错Can't find library

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#553]
**Steps to Reproduce**
```bash
jtreg test/hotspot/jtreg/runtime/appcds/TestCombinedCompressedFlags.java
```

![image](https://user-images.githubusercontent.com/24123821/236783543-e5de614d-38ba-4ee6-8af4-5d567bc8acb0.png)

![image](https://user-images.githubusercontent.com/24123821/236783788-314ceb1c-8293-4e33-b8b1-6ad437398263.png)

2个用例：
![image](https://user-images.githubusercontent.com/24123821/236784633-997181c0-f4ac-46c1-9306-cb268110f3fb.png)

**Comment by zhengxiaolinX** [comment]
The other one `TestZGCWithCDS.java` is also fixed and pushed to the `wip_dragonwell_extended_merge_branch`.
