### ISSUE TITLE
[Bug] 版本号信息错误

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#730]
```bash
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-56/OpenJDK11U-jdk_x64_linux_dragonwell_2023-11-20-06-42.tar.gz
tar xf OpenJDK11U-jdk_x64_linux_dragonwell_2023-11-20-06-42.tar.gz
java -version ; java -Xinternalversion
```

实际结果：

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/2c3834f9-7781-494b-9f4b-5839ea97f8c5)

temurin11结果：

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/594ef2ba-a289-433e-9798-2198d812229d)

**Comment by Accelerator1996** [comment]
个别机器环境问题
