### ISSUE TITLE
[upstream]fastdebug二进制-Xcomp选项运行art-test用例586-checker-null-array-get报错assert(x->type()->tag() == f->type()->tag()) failed: should have same type

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#741]
**Description**

**Steps to Reproduce**
/home/yansendao.ysd/git/jdk11u/build/linux-x86_64-normal-server-fastdebug/images/jdk/bin/java -Xcomp -cp classes:test.jar:test1.jar Main args

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/b76a4cb9-12b7-4056-90d3-7657325d64ee)

[586-checker-null-array-get.zip](https://github.com/dragonwell-project/dragonwell11/files/13682237/586-checker-null-array-get.zip)

**JDK version**
代码版本：

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/07996521-6821-4293-8fd3-71e2548cae56)

**Comment by sendaoYan** [comment]
社区主干已经修复

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/6396d85e-a776-4d19-ad4f-71dd903033e3)

**Comment by kuaiwei** [comment]
It's reported in https://bugs.openjdk.org/browse/JDK-8237894. And fix is https://hg.openjdk.org/jdk/jdk/rev/7e5a53043493 .
We need backport it.
