### ISSUE TITLE
[Bug] Make jdk image时编译失败

### ISSUE THREAD

**Issue by hustbeef** [dragonwell-project/dragonwell11#787]
**Description**
通过 sh make.sh release 编译时，会报错：
Building target 'images' in configuration 'linux-x86_64-normal-server-release'
/usr/bin/bash: -c: line 12: syntax error: unexpected end of file
gmake[3]: *** [GenerateLinkOptData.gmk:64: /home/liuxialin/workspace/projects/ali-dragonwell11/build/linux-x86_64-normal-server-release/support/link_opt/classlist] Error 2
gmake[2]: *** [make/Main.gmk:508: generate-link-opt-data] Error 2
gmake[2]: *** Waiting for unfinished jobs....

这个报错比较简陋，我在backport [JDK-8204564](https://hg.openjdk.org/jdk/jdk/rev/9ee67f08fdaa)后获得了更多信息，如附上的截图
报错：
<img width="1267" alt="launcherHelper" src="https://github.com/dragonwell-project/dragonwell11/assets/52040833/260aee0e-e02d-4fa6-b86d-1119df1a5d81">

这个问题可以100%复现，只需要修改
src/java.base/share/classes/sun/launcher/LauncherHelper.java 中 
         private static Class<?> loadMainClass(int mode, String what);

```
try {
            throw new LinkageError("new linkageERROR");
} catch (LinkageError le) {
            getLocalizedMessage("Will fail");
}
```

<img width="985" alt="image" src="https://github.com/dragonwell-project/dragonwell11/assets/52040833/d3fdb36e-2bcc-4c1e-a301-4c87966c602e">

**Comment by hustbeef** [comment]
根据其它实验，openjdk上游问题无法复现，目前仅在dragonwell中会出现，期待大佬们的答复。

**Comment by kuaiwei** [comment]
我在linux x86和aarch64上执行sh make.sh release都可以正常编译。你的编译环境是什么？os, gcc, bootjdk的版本信息提供一下呢？

**Comment by hustbeef** [comment]
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
目标：x86_64-redhat-linux
配置为：../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://cloud.tencent.com/product/ts --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 8.5.0 20210514

**Comment by hustbeef** [comment]
@kuaiwei 感谢回复，我的环境配置是：
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
目标：x86_64-redhat-linux
配置为：../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://cloud.tencent.com/product/ts --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 8.5.0 20210514 

BOOT_JDK：

**Comment by hustbeef** [comment]
> **Description** 通过 sh make.sh release 编译时，会报错： Building target 'images' in configuration 'linux-x86_64-normal-server-release' /usr/bin/bash: -c: line 12: syntax error: unexpected end of file gmake[3]: *** [GenerateLinkOptData.gmk:64: /home/liuxialin/workspace/projects/ali-dragonwell11/build/linux-x86_64-normal-server-release/support/link_opt/classlist] Error 2 gmake[2]: *** [make/Main.gmk:508: generate-link-opt-data] Error 2 gmake[2]: *** Waiting for unfinished jobs....
> 
> 这个报错比较简陋，我在backport [JDK-8204564](https://hg.openjdk.org/jdk/jdk/rev/9ee67f08fdaa)后获得了更多信息，如附上的截图 报错： <img alt="launcherHelper" width="1267" src="https://private-user-images.githubusercontent.com/52040833/299930641-260aee0e-e02d-4fa6-b86d-1119df1a5d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTEyODAsIm5iZiI6MTcwNjY5MDk4MCwicGF0aCI6Ii81MjA0MDgzMy8yOTk5MzA2NDEtMjYwYWVlMGUtZTAyZC00ZmE2LWI4NmQtMTExOWRmMWE1ZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA4NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYWYwYTAyZGI0MTAzMjQ2YjYzODY5ZDFhNmMwNGVkNmY1NTNjOTgyZGIwZTNiNzU2ZjQzODA2ZDYzOWU1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2rVLfLkX5cw0A3jcBQlb26ZQFpgmhr01j4j4JiqE9aU">
> 
> 这个问题可以100%复现，只需要修改 src/java.base/share/classes/sun/launcher/LauncherHelper.java 中 private static Class<?> loadMainClass(int mode, String what);
> 
> ```
> try {
>             throw new LinkageError("new linkageERROR");
> } catch (LinkageError le) {
>             getLocalizedMessage("Will fail");
> }
> ```
> 
> <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/52040833/299931986-d3fdb36e-2bcc-4c1e-a301-4c87966c602e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTEyODAsIm5iZiI6MTcwNjY5MDk4MCwicGF0aCI6Ii81MjA0MDgzMy8yOTk5MzE5ODYtZDNmZGIzNmUtMmJjYy00YzFlLWEzMDEtNGM4Nzk2NmM2MDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA4NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNWNkNmZjOThkMTE1N2MwMGU5Mjk1NTAwNTFhZDA3YWI4NjMyYjliZDE1Y2ZjNjZhYTM0MWMzNTJiYzFjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2vkLiJQ0aMefn5xAB-a0JBTPw2iNmu2TyKIIGqzHTXM">

最开始暴露问题是因为配置JNI在错误的目录，导致LauncherHelper. loadMainClass()抛出LinkageError，代码中catch LinkageError后调用getLocalizedMessage()会触发了这个问题。所以后续修改loadMainClass为直接调用getLocalizedMessage，复现。

**Comment by kuaiwei** [comment]
这是你修改代码后引入的错误，不是原有代码的错误。

**Comment by kuaiwei** [comment]
不修改Dragonwell的代码，你能运行sh make.sh release吗？
