### ISSUE TITLE
backport问题：dragonwell-extended-11.0.18.14_jdk-11.0.18-ga

### ISSUE THREAD

**Issue by yiiqian** [dragonwell-project/dragonwell11#884]
我在backport dragonwell8的多租户特性，是基于tag dragonwell-extended-11.0.18.14_jdk-11.0.18-ga做的，有dragonwell-extended-11.0.18.14_jdk-11.0.18-ga关联分支吗，我提pull request应该提到哪个分支

**Comment by lingjun-cg** [comment]
由于容器化技术的普遍所以租户特性已经很少有应用场景，所以Dragonwell 11不再合入租户特性。
PR应基于master提交，这个tag dragonwell-extended-11.0.18.14_jdk-11.0.18-ga仅用于发布使用。
